import 'models/level_models.dart';

/// Handcrafted level blueprint. Add new entries to extend content without
/// changing gameplay code.
class LevelBlueprint {
  const LevelBlueprint({
    required this.name,
    required this.objective,
    required this.spawnInterval,
    required this.antSpeedMin,
    required this.antSpeedMax,
    required this.beeSpawnChance,
    required this.maxSimultaneousEnemies,
    required this.lives,
    required this.oneStar,
    required this.twoStar,
    required this.threeStar,
    this.enemyTypes = const [EnemyType.ant],
    this.countdownSeconds,
    this.isBossLevel = false,
  });

  final String name;
  final LevelObjective objective;
  final List<EnemyType> enemyTypes;
  final double spawnInterval;
  final double antSpeedMin;
  final double antSpeedMax;
  final double beeSpawnChance;
  final int maxSimultaneousEnemies;
  final int lives;
  final int oneStar;
  final int twoStar;
  final int threeStar;
  final double? countdownSeconds;
  final bool isBossLevel;
}

/// All 60 handcrafted level blueprints grouped by world.
class LevelBlueprintRegistry {
  LevelBlueprintRegistry._();

  static const Map<int, List<LevelBlueprint>> byWorld = {
    1: _world1,
    2: _world2,
    3: _world3,
    4: _world4,
    5: _world5,
    6: _world6,
  };

  // World 1 – Kitchen (Beginner)
  static const _world1 = [
    LevelBlueprint(
      name: 'First Swat',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 5,
      ),
      spawnInterval: 2.0,
      antSpeedMin: 90,
      antSpeedMax: 120,
      beeSpawnChance: 0,
      maxSimultaneousEnemies: 3,
      lives: 10,
      oneStar: 5,
      twoStar: 8,
      threeStar: 12,
    ),
    LevelBlueprint(
      name: 'Counter Patrol',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 8,
      ),
      spawnInterval: 1.8,
      antSpeedMin: 95,
      antSpeedMax: 125,
      beeSpawnChance: 0,
      maxSimultaneousEnemies: 4,
      lives: 10,
      oneStar: 8,
      twoStar: 12,
      threeStar: 16,
    ),
    LevelBlueprint(
      name: 'Pantry Raid',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 10,
      ),
      spawnInterval: 1.7,
      antSpeedMin: 100,
      antSpeedMax: 130,
      beeSpawnChance: 0.05,
      maxSimultaneousEnemies: 4,
      lives: 9,
      oneStar: 10,
      twoStar: 15,
      threeStar: 20,
    ),
    LevelBlueprint(
      name: 'Sugar Rush',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 12,
      ),
      spawnInterval: 1.6,
      antSpeedMin: 105,
      antSpeedMax: 135,
      beeSpawnChance: 0.05,
      maxSimultaneousEnemies: 5,
      lives: 9,
      oneStar: 12,
      twoStar: 18,
      threeStar: 24,
    ),
    LevelBlueprint(
      name: 'Spill Zone',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 18,
      ),
      spawnInterval: 1.5,
      antSpeedMin: 110,
      antSpeedMax: 140,
      beeSpawnChance: 0.08,
      maxSimultaneousEnemies: 5,
      lives: 8,
      oneStar: 18,
      twoStar: 25,
      threeStar: 32,
    ),
    LevelBlueprint(
      name: 'Crumb Trail',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 15,
      ),
      spawnInterval: 1.4,
      antSpeedMin: 115,
      antSpeedMax: 145,
      beeSpawnChance: 0.08,
      maxSimultaneousEnemies: 5,
      lives: 8,
      oneStar: 15,
      twoStar: 22,
      threeStar: 30,
    ),
    LevelBlueprint(
      name: 'Stove Top',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 25,
      ),
      spawnInterval: 1.35,
      antSpeedMin: 120,
      antSpeedMax: 150,
      beeSpawnChance: 0.1,
      maxSimultaneousEnemies: 6,
      lives: 8,
      oneStar: 25,
      twoStar: 35,
      threeStar: 45,
    ),
    LevelBlueprint(
      name: 'Fridge Front',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 18,
      ),
      spawnInterval: 1.3,
      antSpeedMin: 125,
      antSpeedMax: 155,
      beeSpawnChance: 0.1,
      maxSimultaneousEnemies: 6,
      lives: 7,
      oneStar: 18,
      twoStar: 28,
      threeStar: 38,
    ),
    LevelBlueprint(
      name: 'Midnight Snack',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 35,
      ),
      spawnInterval: 1.25,
      antSpeedMin: 130,
      antSpeedMax: 160,
      beeSpawnChance: 0.12,
      maxSimultaneousEnemies: 6,
      lives: 7,
      oneStar: 35,
      twoStar: 48,
      threeStar: 60,
    ),
    LevelBlueprint(
      name: 'Kitchen Cleanup',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 22,
      ),
      spawnInterval: 1.2,
      antSpeedMin: 135,
      antSpeedMax: 165,
      beeSpawnChance: 0.12,
      maxSimultaneousEnemies: 7,
      lives: 7,
      oneStar: 22,
      twoStar: 35,
      threeStar: 50,
    ),
  ];

  // World 2 – Living Room
  static const _world2 = [
    LevelBlueprint(
      name: 'Carpet Crawlers',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 20,
      ),
      spawnInterval: 1.2,
      antSpeedMin: 140,
      antSpeedMax: 170,
      beeSpawnChance: 0.1,
      maxSimultaneousEnemies: 6,
      lives: 7,
      oneStar: 20,
      twoStar: 30,
      threeStar: 42,
    ),
    LevelBlueprint(
      name: 'Sofa Scouts',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 20,
      ),
      spawnInterval: 1.15,
      antSpeedMin: 145,
      antSpeedMax: 175,
      beeSpawnChance: 0.12,
      maxSimultaneousEnemies: 7,
      lives: 7,
      oneStar: 20,
      twoStar: 32,
      threeStar: 45,
    ),
    LevelBlueprint(
      name: 'TV Stand',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 30,
      ),
      spawnInterval: 1.1,
      antSpeedMin: 150,
      antSpeedMax: 180,
      beeSpawnChance: 0.14,
      maxSimultaneousEnemies: 7,
      lives: 6,
      oneStar: 30,
      twoStar: 42,
      threeStar: 55,
    ),
    LevelBlueprint(
      name: 'Bookshelf Bugs',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 25,
      ),
      spawnInterval: 1.05,
      antSpeedMin: 155,
      antSpeedMax: 185,
      beeSpawnChance: 0.15,
      maxSimultaneousEnemies: 8,
      lives: 6,
      oneStar: 25,
      twoStar: 38,
      threeStar: 52,
    ),
    LevelBlueprint(
      name: 'Window Sill',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateBees,
        targetBees: 5,
      ),
      spawnInterval: 1.0,
      antSpeedMin: 160,
      antSpeedMax: 190,
      beeSpawnChance: 0.35,
      maxSimultaneousEnemies: 8,
      lives: 6,
      oneStar: 12,
      twoStar: 18,
      threeStar: 25,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Lamp Light',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 40,
      ),
      spawnInterval: 0.95,
      antSpeedMin: 165,
      antSpeedMax: 195,
      beeSpawnChance: 0.18,
      maxSimultaneousEnemies: 8,
      lives: 6,
      oneStar: 40,
      twoStar: 55,
      threeStar: 70,
    ),
    LevelBlueprint(
      name: 'Rug Runners',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 30,
      ),
      spawnInterval: 0.9,
      antSpeedMin: 170,
      antSpeedMax: 200,
      beeSpawnChance: 0.2,
      maxSimultaneousEnemies: 9,
      lives: 5,
      oneStar: 30,
      twoStar: 45,
      threeStar: 60,
    ),
    LevelBlueprint(
      name: 'Curtain Call',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateAnts,
        targetAnts: 25,
      ),
      spawnInterval: 0.88,
      antSpeedMin: 175,
      antSpeedMax: 205,
      beeSpawnChance: 0.1,
      maxSimultaneousEnemies: 9,
      lives: 5,
      oneStar: 25,
      twoStar: 35,
      threeStar: 48,
    ),
    LevelBlueprint(
      name: 'Coffee Table',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 55,
      ),
      spawnInterval: 0.85,
      antSpeedMin: 180,
      antSpeedMax: 210,
      beeSpawnChance: 0.22,
      maxSimultaneousEnemies: 9,
      lives: 5,
      oneStar: 55,
      twoStar: 72,
      threeStar: 90,
    ),
    LevelBlueprint(
      name: 'Living Room Finale',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 35,
      ),
      spawnInterval: 0.8,
      antSpeedMin: 185,
      antSpeedMax: 215,
      beeSpawnChance: 0.25,
      maxSimultaneousEnemies: 10,
      lives: 5,
      oneStar: 35,
      twoStar: 55,
      threeStar: 75,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
  ];

  // World 3 – Garden
  static const _world3 = [
    LevelBlueprint(
      name: 'Flower Bed',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateAnts,
        targetAnts: 15,
      ),
      spawnInterval: 0.85,
      antSpeedMin: 160,
      antSpeedMax: 200,
      beeSpawnChance: 0.15,
      maxSimultaneousEnemies: 8,
      lives: 6,
      oneStar: 15,
      twoStar: 22,
      threeStar: 30,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Bee Hive',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateBees,
        targetBees: 8,
      ),
      spawnInterval: 0.8,
      antSpeedMin: 165,
      antSpeedMax: 205,
      beeSpawnChance: 0.45,
      maxSimultaneousEnemies: 9,
      lives: 6,
      oneStar: 20,
      twoStar: 30,
      threeStar: 42,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Mulch Maze',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 12,
        targetBees: 5,
      ),
      spawnInterval: 0.78,
      antSpeedMin: 170,
      antSpeedMax: 210,
      beeSpawnChance: 0.3,
      maxSimultaneousEnemies: 9,
      lives: 5,
      oneStar: 25,
      twoStar: 38,
      threeStar: 52,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Sprinkler Sprint',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 50,
      ),
      spawnInterval: 0.75,
      antSpeedMin: 175,
      antSpeedMax: 215,
      beeSpawnChance: 0.28,
      maxSimultaneousEnemies: 10,
      lives: 5,
      oneStar: 50,
      twoStar: 68,
      threeStar: 88,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Compost Corner',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 35,
      ),
      spawnInterval: 0.72,
      antSpeedMin: 180,
      antSpeedMax: 220,
      beeSpawnChance: 0.3,
      maxSimultaneousEnemies: 10,
      lives: 5,
      oneStar: 35,
      twoStar: 52,
      threeStar: 70,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Rose Bush',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 18,
        targetBees: 8,
      ),
      spawnInterval: 0.7,
      antSpeedMin: 185,
      antSpeedMax: 225,
      beeSpawnChance: 0.32,
      maxSimultaneousEnemies: 11,
      lives: 5,
      oneStar: 40,
      twoStar: 58,
      threeStar: 78,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Greenhouse',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 65,
      ),
      spawnInterval: 0.68,
      antSpeedMin: 190,
      antSpeedMax: 230,
      beeSpawnChance: 0.35,
      maxSimultaneousEnemies: 11,
      lives: 4,
      oneStar: 65,
      twoStar: 85,
      threeStar: 105,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Pond Edge',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateBees,
        targetBees: 12,
      ),
      spawnInterval: 0.65,
      antSpeedMin: 195,
      antSpeedMax: 235,
      beeSpawnChance: 0.5,
      maxSimultaneousEnemies: 12,
      lives: 4,
      oneStar: 30,
      twoStar: 45,
      threeStar: 60,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Garden Gate',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 45,
      ),
      spawnInterval: 0.62,
      antSpeedMin: 200,
      antSpeedMax: 240,
      beeSpawnChance: 0.38,
      maxSimultaneousEnemies: 12,
      lives: 4,
      oneStar: 45,
      twoStar: 65,
      threeStar: 88,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Garden Master',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 25,
        targetBees: 12,
      ),
      spawnInterval: 0.6,
      antSpeedMin: 205,
      antSpeedMax: 245,
      beeSpawnChance: 0.4,
      maxSimultaneousEnemies: 13,
      lives: 4,
      oneStar: 55,
      twoStar: 78,
      threeStar: 100,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
  ];

  // World 4 – Garage
  static const _world4 = [
    LevelBlueprint(
      name: 'Oil Stain',
      objective: LevelObjective(
        type: LevelObjectiveType.surviveTime,
        surviveSeconds: 30,
      ),
      spawnInterval: 0.7,
      antSpeedMin: 200,
      antSpeedMax: 240,
      beeSpawnChance: 0.25,
      maxSimultaneousEnemies: 10,
      lives: 5,
      oneStar: 15,
      twoStar: 25,
      threeStar: 40,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Tool Bench',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 60,
      ),
      spawnInterval: 0.65,
      antSpeedMin: 210,
      antSpeedMax: 250,
      beeSpawnChance: 0.3,
      maxSimultaneousEnemies: 11,
      lives: 5,
      oneStar: 60,
      twoStar: 80,
      threeStar: 100,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Workbench',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 40,
      ),
      spawnInterval: 0.62,
      antSpeedMin: 215,
      antSpeedMax: 255,
      beeSpawnChance: 0.32,
      maxSimultaneousEnemies: 12,
      lives: 4,
      oneStar: 40,
      twoStar: 60,
      threeStar: 82,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Tire Stack',
      objective: LevelObjective(
        type: LevelObjectiveType.surviveTime,
        surviveSeconds: 40,
      ),
      spawnInterval: 0.6,
      antSpeedMin: 220,
      antSpeedMax: 260,
      beeSpawnChance: 0.35,
      maxSimultaneousEnemies: 12,
      lives: 4,
      oneStar: 25,
      twoStar: 40,
      threeStar: 58,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Engine Bay',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 20,
        targetBees: 10,
      ),
      spawnInterval: 0.58,
      antSpeedMin: 225,
      antSpeedMax: 265,
      beeSpawnChance: 0.38,
      maxSimultaneousEnemies: 13,
      lives: 4,
      oneStar: 45,
      twoStar: 65,
      threeStar: 88,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Chain Hoist',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 80,
      ),
      spawnInterval: 0.55,
      antSpeedMin: 230,
      antSpeedMax: 270,
      beeSpawnChance: 0.4,
      maxSimultaneousEnemies: 13,
      lives: 4,
      oneStar: 80,
      twoStar: 105,
      threeStar: 130,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Workbench Rush',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 50,
      ),
      spawnInterval: 0.52,
      antSpeedMin: 235,
      antSpeedMax: 275,
      beeSpawnChance: 0.42,
      maxSimultaneousEnemies: 14,
      lives: 3,
      oneStar: 50,
      twoStar: 72,
      threeStar: 95,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Garage Gauntlet',
      objective: LevelObjective(
        type: LevelObjectiveType.surviveTime,
        surviveSeconds: 50,
      ),
      spawnInterval: 0.5,
      antSpeedMin: 240,
      antSpeedMax: 280,
      beeSpawnChance: 0.45,
      maxSimultaneousEnemies: 14,
      lives: 3,
      oneStar: 35,
      twoStar: 55,
      threeStar: 78,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Power Tools',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 100,
      ),
      spawnInterval: 0.48,
      antSpeedMin: 245,
      antSpeedMax: 285,
      beeSpawnChance: 0.48,
      maxSimultaneousEnemies: 15,
      lives: 3,
      oneStar: 100,
      twoStar: 130,
      threeStar: 160,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Garage Boss',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 30,
        targetBees: 15,
      ),
      spawnInterval: 0.45,
      antSpeedMin: 250,
      antSpeedMax: 290,
      beeSpawnChance: 0.5,
      maxSimultaneousEnemies: 15,
      lives: 3,
      oneStar: 65,
      twoStar: 95,
      threeStar: 125,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
  ];

  // World 5 – Laboratory
  static const _world5 = [
    LevelBlueprint(
      name: 'Test Tube',
      objective: LevelObjective(
        type: LevelObjectiveType.countdownComplete,
        targetScore: 50,
        countdownSeconds: 60,
      ),
      spawnInterval: 0.55,
      antSpeedMin: 230,
      antSpeedMax: 270,
      beeSpawnChance: 0.35,
      maxSimultaneousEnemies: 12,
      lives: 4,
      oneStar: 50,
      twoStar: 70,
      threeStar: 90,
      countdownSeconds: 60,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Petri Dish',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 45,
      ),
      spawnInterval: 0.52,
      antSpeedMin: 235,
      antSpeedMax: 275,
      beeSpawnChance: 0.38,
      maxSimultaneousEnemies: 13,
      lives: 4,
      oneStar: 45,
      twoStar: 65,
      threeStar: 88,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Microscope',
      objective: LevelObjective(
        type: LevelObjectiveType.countdownComplete,
        targetCount: 40,
        countdownSeconds: 55,
      ),
      spawnInterval: 0.5,
      antSpeedMin: 240,
      antSpeedMax: 280,
      beeSpawnChance: 0.4,
      maxSimultaneousEnemies: 13,
      lives: 3,
      oneStar: 40,
      twoStar: 58,
      threeStar: 78,
      countdownSeconds: 55,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Chemical Spill',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 25,
        targetBees: 12,
      ),
      spawnInterval: 0.48,
      antSpeedMin: 245,
      antSpeedMax: 285,
      beeSpawnChance: 0.42,
      maxSimultaneousEnemies: 14,
      lives: 3,
      oneStar: 55,
      twoStar: 78,
      threeStar: 100,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Bunsen Burner',
      objective: LevelObjective(
        type: LevelObjectiveType.countdownComplete,
        targetScore: 80,
        countdownSeconds: 50,
      ),
      spawnInterval: 0.46,
      antSpeedMin: 250,
      antSpeedMax: 290,
      beeSpawnChance: 0.45,
      maxSimultaneousEnemies: 14,
      lives: 3,
      oneStar: 80,
      twoStar: 105,
      threeStar: 130,
      countdownSeconds: 50,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Specimen Jar',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateBees,
        targetBees: 18,
      ),
      spawnInterval: 0.44,
      antSpeedMin: 255,
      antSpeedMax: 295,
      beeSpawnChance: 0.55,
      maxSimultaneousEnemies: 15,
      lives: 3,
      oneStar: 45,
      twoStar: 65,
      threeStar: 88,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'DNA Strand',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 55,
      ),
      spawnInterval: 0.42,
      antSpeedMin: 260,
      antSpeedMax: 300,
      beeSpawnChance: 0.48,
      maxSimultaneousEnemies: 15,
      lives: 3,
      oneStar: 55,
      twoStar: 78,
      threeStar: 102,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Containment',
      objective: LevelObjective(
        type: LevelObjectiveType.countdownComplete,
        targetCount: 50,
        countdownSeconds: 45,
      ),
      spawnInterval: 0.4,
      antSpeedMin: 265,
      antSpeedMax: 305,
      beeSpawnChance: 0.5,
      maxSimultaneousEnemies: 16,
      lives: 2,
      oneStar: 50,
      twoStar: 72,
      threeStar: 95,
      countdownSeconds: 45,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Mutation Chamber',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 120,
      ),
      spawnInterval: 0.38,
      antSpeedMin: 270,
      antSpeedMax: 310,
      beeSpawnChance: 0.52,
      maxSimultaneousEnemies: 16,
      lives: 2,
      oneStar: 120,
      twoStar: 155,
      threeStar: 190,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Lab Lockdown',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 35,
        targetBees: 18,
      ),
      spawnInterval: 0.36,
      antSpeedMin: 275,
      antSpeedMax: 315,
      beeSpawnChance: 0.55,
      maxSimultaneousEnemies: 17,
      lives: 2,
      oneStar: 80,
      twoStar: 115,
      threeStar: 150,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
  ];

  // World 6 – Boss Challenge
  static const _world6 = [
    LevelBlueprint(
      name: 'Elite Scout',
      objective: LevelObjective(
        type: LevelObjectiveType.smashCount,
        targetCount: 50,
      ),
      spawnInterval: 0.4,
      antSpeedMin: 280,
      antSpeedMax: 320,
      beeSpawnChance: 0.45,
      maxSimultaneousEnemies: 14,
      lives: 3,
      oneStar: 50,
      twoStar: 72,
      threeStar: 95,
      enemyTypes: [EnemyType.ant, EnemyType.bee],
    ),
    LevelBlueprint(
      name: 'Swarm Captain',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateBees,
        targetBees: 20,
      ),
      spawnInterval: 0.38,
      antSpeedMin: 285,
      antSpeedMax: 325,
      beeSpawnChance: 0.6,
      maxSimultaneousEnemies: 15,
      lives: 3,
      oneStar: 55,
      twoStar: 78,
      threeStar: 102,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
    ),
    LevelBlueprint(
      name: 'Iron Ant',
      objective: LevelObjective(
        type: LevelObjectiveType.countdownComplete,
        targetScore: 100,
        countdownSeconds: 50,
      ),
      spawnInterval: 0.36,
      antSpeedMin: 290,
      antSpeedMax: 330,
      beeSpawnChance: 0.5,
      maxSimultaneousEnemies: 15,
      lives: 2,
      oneStar: 100,
      twoStar: 130,
      threeStar: 165,
      countdownSeconds: 50,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
    ),
    LevelBlueprint(
      name: 'Queen Bee',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 30,
        targetBees: 20,
      ),
      spawnInterval: 0.34,
      antSpeedMin: 295,
      antSpeedMax: 335,
      beeSpawnChance: 0.55,
      maxSimultaneousEnemies: 16,
      lives: 2,
      oneStar: 85,
      twoStar: 120,
      threeStar: 155,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
      isBossLevel: true,
    ),
    LevelBlueprint(
      name: 'Chaos Protocol',
      objective: LevelObjective(
        type: LevelObjectiveType.surviveTime,
        surviveSeconds: 60,
      ),
      spawnInterval: 0.32,
      antSpeedMin: 300,
      antSpeedMax: 340,
      beeSpawnChance: 0.58,
      maxSimultaneousEnemies: 17,
      lives: 2,
      oneStar: 50,
      twoStar: 75,
      threeStar: 105,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
    ),
    LevelBlueprint(
      name: 'Final Stand',
      objective: LevelObjective(
        type: LevelObjectiveType.countdownComplete,
        targetCount: 60,
        countdownSeconds: 45,
      ),
      spawnInterval: 0.3,
      antSpeedMin: 305,
      antSpeedMax: 345,
      beeSpawnChance: 0.6,
      maxSimultaneousEnemies: 17,
      lives: 2,
      oneStar: 60,
      twoStar: 88,
      threeStar: 115,
      countdownSeconds: 45,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
    ),
    LevelBlueprint(
      name: 'Mega Swarm',
      objective: LevelObjective(
        type: LevelObjectiveType.targetScore,
        targetScore: 150,
      ),
      spawnInterval: 0.28,
      antSpeedMin: 310,
      antSpeedMax: 350,
      beeSpawnChance: 0.62,
      maxSimultaneousEnemies: 18,
      lives: 2,
      oneStar: 150,
      twoStar: 190,
      threeStar: 230,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
    ),
    LevelBlueprint(
      name: 'Titan Bug',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 40,
        targetBees: 25,
      ),
      spawnInterval: 0.26,
      antSpeedMin: 315,
      antSpeedMax: 355,
      beeSpawnChance: 0.65,
      maxSimultaneousEnemies: 18,
      lives: 2,
      oneStar: 100,
      twoStar: 140,
      threeStar: 180,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
      isBossLevel: true,
    ),
    LevelBlueprint(
      name: 'Apocalypse',
      objective: LevelObjective(
        type: LevelObjectiveType.countdownComplete,
        targetScore: 180,
        countdownSeconds: 40,
      ),
      spawnInterval: 0.24,
      antSpeedMin: 320,
      antSpeedMax: 360,
      beeSpawnChance: 0.68,
      maxSimultaneousEnemies: 19,
      lives: 1,
      oneStar: 180,
      twoStar: 225,
      threeStar: 270,
      countdownSeconds: 40,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
    ),
    LevelBlueprint(
      name: 'Ultimate Boss',
      objective: LevelObjective(
        type: LevelObjectiveType.eliminateMixed,
        targetAnts: 45,
        targetBees: 30,
      ),
      spawnInterval: 0.22,
      antSpeedMin: 330,
      antSpeedMax: 370,
      beeSpawnChance: 0.7,
      maxSimultaneousEnemies: 20,
      lives: 1,
      oneStar: 120,
      twoStar: 170,
      threeStar: 220,
      enemyTypes: [EnemyType.ant, EnemyType.bee, EnemyType.boss],
      isBossLevel: true,
    ),
  ];
}
